contact_links:
  - name: ğŸ’¬ Question
    url:  https://gitter.im/stdlib-js/stdlib
    about: Got a question? Ask us on Gitter! ğŸ¤—
  - name: Frequently Asked Questions
    url:  https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md
    about: Be sure to consult the FAQ in case we have already answered your question there.
  - name: ğŸ‘ Support Us
    url: https://github.com/stdlib-js/stdlib/blob/develop/.github/ISSUE_TEMPLATE/support_the_project.md
    about: Want to help support the project? ğŸ˜


